### ISSUE TITLE
Exclude a class property

### ISSUE THREAD

**Issue by ukienet** [Nukepayload2/Nukepayload2.Csv#3]
Hi, I have a class property that I want to exclude during serialization, can it be done?

**Comment by Nukepayload2** [comment]
You can use the `CsvIgnoreAttribute` to exclude the annotated property.

https://github.com/Nukepayload2/Nukepayload2.Csv/blob/2ee6bf7b539675ace8a49caaa555e22d56293d0d/Nukepayload2.Csv.TestCommon/OptInSerializationModel.vb#L37
